before_script:
  - "mysql -e 'create database katalog_test;' > /dev/null"
  - bundle exec rake bookyt:setup
  - RAILS_ENV=development bundle exec rake db:schema:load

script: "bundle exec rake test"

# whitelist
branches:
  only:
    - master
    - stable

rvm:
  - 1.8.7 # (current default)
  - 1.9.2

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
